CC = gcc
OBJS = esp.o decryptor.o encryptor.o authenticator.o s_window.o SAD.o SPD.o
SRCS = $(OBJS:%.o=%.c)
TARGET = IPSec_module
 
.SUFFIXES : .c .o
 
all : $(TARGET)

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

depend : 
	gccmakedep $(SRCS)
				 
clean :
	rm -f $(OBJS) $(TARGET)
		 
